export const FETCH_PAGES = 'FETCH_PAGES'
export const FETCH_MENU = 'FETCH_MENU'
export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_VIDEOS = 'FETCH_VIDEOS'
export const FETCH_INSTA = 'FETCH_INSTA'

export const REQUEST_PAGES = 'REQUEST_PAGES'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const REQUEST_VIDEOS = 'REQUEST_VIDEOS'
export const REQUEST_INSTA = 'REQUEST_INSTA'

export const FETCH_ERROR = 'FETCH_ERROR'
